import "./globals.css";
import type { Metadata } from "next";
import { cal, inter } from "@/styles/fonts";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(cal.variable, inter.variable)}>{children}</body>
    </html>
  );
}
